# Typing stubs for the condeltri pybind11 extension module.
# Signatures mirror cdt_bindings.cpp; keep the two in sync.

import enum
from collections.abc import Iterator
from typing import overload

from typing_extensions import Buffer

NO_VERTEX: int
NO_NEIGHBOR: int

class VertexInsertionOrder(enum.IntEnum):
    AUTO = 0
    AS_PROVIDED = 1

class IntersectingConstraintEdges(enum.IntEnum):
    NOT_ALLOWED = 0
    TRY_RESOLVE = 1
    DONT_CHECK = 2

class V2d:
    x: float
    y: float
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, arg0: Buffer, /) -> None: ...
    def __repr__(self) -> str: ...

class Edge:
    @property
    def v1(self) -> int: ...
    @property
    def v2(self) -> int: ...
    @overload
    def __init__(self, index_vert_a: int, index_vert_b: int) -> None: ...
    @overload
    def __init__(self, arg0: Buffer, /) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Triangle:
    vertices: list[int]
    neighbors: list[int]
    def __repr__(self) -> str: ...

class Triangulation:
    def __init__(
        self,
        vertex_insertion_order: VertexInsertionOrder,
        intersecting_edges_strategy: IntersectingConstraintEdges,
        min_dist_to_constraint_edge: float,
    ) -> None: ...
    @property
    def vertices(self) -> list[V2d]: ...
    @property
    def triangles(self) -> list[Triangle]: ...
    @property
    def fixed_edges(self) -> set[Edge]: ...
    @property
    def overlap_count(self) -> dict[Edge, int]: ...
    @property
    def piece_to_originals(self) -> dict[Edge, list[Edge]]: ...
    @overload
    def insert_vertices(self, vertices: list[V2d]) -> None: ...
    @overload
    def insert_vertices(self, vertex_buffer: Buffer) -> None: ...
    @overload
    def insert_edges(self, edges: list[Edge]) -> None: ...
    @overload
    def insert_edges(self, edge_buffer: Buffer) -> None: ...
    @overload
    def conform_to_edges(self, edges: list[Edge]) -> None: ...
    @overload
    def conform_to_edges(self, edge_buffer: Buffer) -> None: ...
    def erase_super_triangle(self) -> None: ...
    def erase_outer_triangles(self) -> None: ...
    def erase_outer_triangles_and_holes(self) -> None: ...
    def calculate_triangle_depths(self) -> list[int]: ...
    def remove_triangles(self, triangle_indices: set[int]) -> None: ...
    def is_finalized(self) -> bool: ...
    def vertices_count(self) -> int: ...
    def vertices_iter(self) -> Iterator[V2d]: ...
    def triangles_count(self) -> int: ...
    def triangles_iter(self) -> Iterator[Triangle]: ...
    def fixed_edges_count(self) -> int: ...
    def fixed_edges_iter(self) -> Iterator[Edge]: ...
    def overlap_count_count(self) -> int: ...
    def overlap_count_iter(self) -> Iterator[tuple[Edge, int]]: ...
    def piece_to_originals_count(self) -> int: ...
    def piece_to_originals_iter(self) -> Iterator[tuple[Edge, list[Edge]]]: ...

def verify_topology(triangulation: Triangulation) -> bool: ...
