name: Publish Python distribution to TestPyPI

# on: push

jobs:
  download-wheels:
    name: Get the pre-built wheels
    runs-on: ubuntu-latest

    # this must match the cibuildwheel.yml section
    strategy:
      matrix:
        # os: [ linux-intel, linux-arm, windows, macOS-intel, macOS-arm ]
        os: [ linux-intel, windows ]
        include:
          - archs: auto
            platform: auto
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: windows
            runs-on: windows-latest
          - os: macos-intel
            # macos-13 was the last x86_64 runner
            runs-on: macos-13
          - os: macos-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
            archs: auto,universal2

    steps:
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: wheelhouse/
  
  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/PythonCDT

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download source distribution
      uses: actions/download-artifact@v4
      with:
        name: cibw-sdist
        path: wheelhouse/
    - name: Publish all the dists
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
